name: Unit Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.12']

    timeout-minutes: 10

    steps:
      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Export Display
        run: export DISPLAY=':99.0'

      - name: Setup xvfb
        run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Create venv
        run: uv venv

      - name: Install tk_tools
        run: uv pip install -e .

      - name: Execute Tests
        # run: uv run pytest -v tests/ --cov=tk_tools
        run: xvfb-run uv run pytest -v tests/ --cov=tk_tools
